/**
 * Extract the build info from the package.json file
 * and write it to a TypeScript file.
 */
// Use ES module imports and __dirname workaround
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const pkg = JSON.parse(
  fs.readFileSync(path.join(__dirname, '../package.json'), 'utf8')
);
const buildInfo = {
  name: pkg.name || '',
  version: pkg.version || '',
  author: pkg.author || '',
  license: pkg.license || '',
  description: pkg.description || '',
};

const buildInfoFileContent = `// This file is automatically generated. DO NOT EDIT.

export const buildInfo = ${JSON.stringify(buildInfo, null, 2)};
`;

const buildInfoPath = path.join(__dirname, '../src/generated/build-info.ts');
fs.writeFileSync(buildInfoPath, buildInfoFileContent, 'utf8');
